AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB table creation for ami_kms_fork_manager
Parameters:
  AmiTableName:
    Type: String
    Description : "Table name for ami_kms_fork_manager"

Resources:
  TrackingTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "sourceami"
          AttributeType: "S"
        - AttributeName: "targetami"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "sourceami"
          KeyType: HASH
        - AttributeName: "targetami"
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref AmiTableName